# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f258b21ff670c165c703a1358fb14e3a62ab9243b015a21a1d7471bae38721a054872b0411237ed0ed156f0eb4a7858bb6f4e4a5759b465f989952f4ee411969

test:
  secret_key_base: a52f62aed8febcd26878621a32e69ffb7f2764f5eacc86a0cea14384a01191132ed712db6f45164162e138754834d9affcbf19ebc2a6436de6baf3542fcf3f7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
